# Generated by Django 2.1.1 on 2018-10-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20181012_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talker', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, max_length=113)),
            ],
        ),
    ]
